// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/health/check": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Check external services statuses",
                "responses": {
                    "200": {
                        "description": "Service healthy",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/communication.ServiceHealthyResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Service non-healthy",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/communication.ServiceHealthyResponse"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "communication.ServiceHealthyResponse": {
            "type": "object",
            "properties": {
                "serviceName": {
                    "type": "string",
                    "example": "redis"
                },
                "status": {
                    "type": "string",
                    "example": "up/down"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
